# Generated by Django 3.2.9 on 2021-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211126_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='current_price',
            field=models.CharField(max_length=200),
        ),
    ]
