# Generated by Django 3.2.9 on 2021-11-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skin_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skin',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='highest_price',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='lowest_price',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='prev_prices',
        ),
    ]
