# Generated by Django 3.2.9 on 2021-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='current_price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
