# Generated by Django 3.2.9 on 2021-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skin_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='current_price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
